-record(counter, {type, count}).
-record(user, {name, id, pass, email, created, last_access}).
-record(domain, {name, id, user_id, created}).
-record(alias, {from, id, to, domain_id, is_active=true, note, created}).
